### ISSUE TITLE
你好，这套系统能用于生产吗？

### ISSUE THREAD

**Issue by fsinbad** [agoodays/agpayplus#1]
你好，

我有几个问题请教一下。

1、这套系统能用于生产吗？

2、有没有大概的Roadmap？

谢谢！

**Comment by xiangyisheng** [comment]
暂时没有，可以用于生产

**Comment by fsinbad** [comment]
感谢回复。

你的代码更新速度、量很惊人。辛苦了！

继续关注、谢谢。

**Comment by xiangyisheng** [comment]
感谢关注，会持续更新
